#
# Docker file to build the Capture environment.
#
####################################################################################################
#
FROM docker.elastic.co/logstash/logstash:6.3.1
#
ADD filesystem /
#
