#
# docker-compose instructions to deploy the product from images
#

version: '3.6'

services:
  capture:
    build:
      context: ./Capture
    image: e2nw/capture
    container_name: e2nwcapture
    depends_on:
      - elasticsearch
    ports:
      - "2055:2055/udp"
      - "5000:5000/tcp"
      - "5000:5000/udp"
    networks:
      - e2netwatch-net
    volumes:
      - ./Capture/filesystem/logstash.conf:/usr/share/logstash/pipeline/logstash.conf


  backend:
    build: 
      context: ./Capture
    image: e2nw/backend
    container_name: e2nwbackend
    depends_on:
      - mysql
      - elasticsearch
    networks:
      - e2netwatch-net

      
  middleware:
    build:
      context: ./Middleware
      args: 
        - VARIANT=dev
    image: e2nw/middleware
    container_name: e2nwmiddleware
    depends_on:
      - mysql
      - elasticsearch
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.proxy
      - ReportsData:/var/lib/jetty/src/files/reports
    networks:
      - e2netwatch-net
  
  
  frontend:
    build:
      context: ./Frontend
    image: e2nw/frontend
    container_name: e2nwfrontend
    depends_on:
      - middleware
    ports:
      - "80:80"
    networks:
      - e2netwatch-net
    
    
  elasticsearch:
    build:
      context: ./Elasticsearch
    image: e2nw/elasticsearch
    container_name: e2nwelasticsearch
    ports:
      - "9200:9200"
    environment:
      - ES_JAVA_OPTS=-Xms${e2nw_ES_MEM:-512m} -Xmx${e2nw_ES_MEM:-512m}
      - cluster.name=e2nw
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ElasticData:/usr/share/elasticsearch/data
    networks:
      - e2netwatch-net
  
  
  kibana:
    build:
      context: ./Kibana
    image: e2nw/kibana
    container_name: e2nwkibana
    depends_on:
      - elasticsearch
    expose:
      - "5601"
    ports: 
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://e2nwelasticsearch:9200
    networks:
      - e2netwatch-net

    
  mysql:
    build:
      context: ./Mysql
    image: e2nw/mysql
    container_name: e2nwmysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    expose:
     - "3306"
    volumes:
      - MysqlData:/var/lib/mysql
      - MysqlBackupData:/backup
    networks:
      - e2netwatch-net

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
       - "2181:2181"
    
  kafka:
    build:
      context: ./Kafka
    ports:
     - "9092"
    environment:

      # Kafka advertised listener MUST be defined in this way 
      # for us to able to skale kafka.
      # TODO: Understand the process more and add more env variables
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  


volumes:
  ElasticData:
  CaptureData:
  MysqlData:
  MysqlBackupData:
  ReportsData:

networks:
  e2netwatch-net:
    name: e2netwatch
