#!/bin/bash

#custom folder can be given by parameters
while getopts d:a:h option
do
	case "${option}"
	in
	d) TEMPLATEFOLDER=${OPTARG};;
	a) NIFIADDRESS=${OPTARG};;
	h) echo -d custom directory, standard is \"templates\" folder in the script\'s Directory; 
		echo -a Nifi-address and port. Current Standard localhost:8090; exit ;;
	esac
done

##gets current directory
ABSPATH=$( realpath $0 )
SCRIPTDIR=$( dirname $ABSPATH )

#sets templatefolder to default Location, if No Argument set
: ${TEMPLATEFOLDER:=$SCRIPTDIR/templates}
#sets NiFi Address and Port to default, if No Argument set
: ${NIFIADDRESS:=http://localhost:8090}

echo uploading Templates from $TEMPLATEFOLDER
echo uploading via NiFiPort $NIFIADDRESS

#uploads Templates from $TEMPLATEFOLDER
for File in $TEMPLATEFOLDER/*.xml; do
		echo uploading $File
		curl -s -X POST \
		 $NIFIADDRESS/nifi-api/process-groups/root/templates/upload \
		 -H 'cache-control: no-cache' \
		 -H 'content-type: multipart/form-data' \
		 -F template=@$File
		 echo 
	done 
