export const GET_USERS_BEGIN = 'GET USERS BEGIN';
export const GET_USERS_SUCCESS = 'GET USERS SUCCESS';
export const GET_USERS_FAILURE = 'GET USERS FAILURE';

export const GET_GLOBAL_PREFERENCES_BEGIN = 'GET GLOBAL PREFERENCES BEGIN';
export const GET_GLOBAL_PREFERENCES_SUCCESS = 'GET GLOBAL PREFERENCES SUCCESS';
export const GET_GLOBAL_PREFERENCES_FAILURE = 'GET GLOBAL PREFERENCES FAILURE';

export const UPDATE_GLOBAL_PREFERENCES_BEGIN = 'GET GLOBAL PREFERENCES BEGIN';
export const UPDATE_GLOBAL_PREFERENCES_SUCCESS = 'GET GLOBAL PREFERENCES SUCCESS';
export const UPDATE_GLOBAL_PREFERENCES_FAILURE = 'GET GLOBAL PREFERENCES FAILURE';

export const GET_USER_BEGIN = 'GET USER BEGIN';
export const GET_USER_SUCCESS = 'GET USER SUCCESS';
export const GET_USER_FAILURE = 'GET USER FAILURE';

export const UPDATE_USER_BEGIN = 'UPDATE USER BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE USER SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE USER FAILURE';

export const GET_USER_PREFERENCES_BEGIN = 'GET USER PREFERENCES BEGIN';
export const GET_USER_PREFERENCES_SUCCESS = 'GET USER PREFERENCES SUCCESS';
export const GET_USER_PREFERENCES_FAILURE = 'GET USER PREFERENCES FAILURE';

export const UPDATE_USER_PREFERENCES_BEGIN = 'UPDATE USER PREFERENCES BEGIN';
export const UPDATE_USER_PREFERENCES_SUCCESS = 'UPDATE USER PREFERENCES SUCCESS';
export const UPDATE_USER_PREFERENCES_FAILURE = 'UPDATE USER PREFERENCES FAILURE';

export const CHANGE_PASSWORD_BEGIN = 'CHANGE PASSWORD BEGIN';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE PASSWORD SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE PASSWORD FAILURE';

export const GET_TIMEZONES_BEGIN = 'GET TIMEZONES BEGIN';
export const GET_TIMEZONES_SUCCESS = 'GET TIMEZONES SUCCESS';
export const GET_TIMEZONES_FAILURE = 'GET TIMEZONES FAILURE';

export const GET_USER_GROUPS_BEGIN = 'GET USER GROUPS BEGIN';
export const GET_USER_GROUPS_SUCCESS = 'GET USER GROUPS SUCCESS';
export const GET_USER_GROUPS_FAILURE = 'GET USER GROUPS FAILURE';

export const ACTIVATE_USER_BEGIN = 'ACTIVATE USER BEGIN';
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE USER SUCCESS';
export const ACTIVATE_USER_FAILURE = 'ACTIVATE USER FAILURE';

export const DEACTIVATE_USER_BEGIN = 'DEACTIVATE USER BEGIN';
export const DEACTIVATE_USER_SUCCESS = 'DEACTIVATE USER SUCCESS';
export const DEACTIVATE_USER_FAILURE = 'DEACTIVATE USER FAILURE';

export const DELETE_USER_BEGIN = 'DELETE USER BEGIN';
export const DELETE_USER_SUCCESS = 'DELETE USER SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE USER FAILURE';

export const ADMIN_UPDATE_USER_BEGIN = 'DELETE USER BEGIN';
export const ADMIN_UPDATE_USER_SUCCESS = 'DELETE USER SUCCESS';
export const ADMIN_UPDATE_USER_FAILURE = 'DELETE USER FAILURE';