#
# Docker file to build the Elasticsearch environment based on Image provided by Elastic
#
####################################################################################################
#
#
FROM docker.elastic.co/logstash/logstash:6.3.1
#
ADD filesystem /
#
#
####################################################################################################
#
# Set the default command.
#
# ENTRYPOINT inherited from original Image
#
####################################################################################################
